### ISSUE TITLE
Meta-Verse Programming? What Connect and Ignite mean for Python Professionals

### ISSUE THREAD

**Issue by kjaymiller** [Python-Community-News/Topics#24]
### Use this checklist to walk through all the steps you'll need to complete for each episode

- [x] Download the Audio/Video from StreamYard
- [x] Share the YouTube link with folks on social media
- [ ] Break the video into chapters
- [ ] Update Timestamps in Shownotes Post
- [x] Publish podcast episode
- [x] Add Github link/podcast url/and YouTube link to content

### Episode Date

2022-10-07

### Podcast

0cab0ba2

### YouTube

-Q6Jvm5cOS0

### Issues

#21, #14, #19, #11, #12

### Conferences
#15, #20, #22, #23

### Newsletter Publish

2022-10-17T08:00-08:00

**Comment by kjaymiller** [comment]
Didn't do chapters on this one. Trying to get the rest of the videos added to the new channel
